services:
  jetbrains-marketplace-stats:
    container_name: jetbrains-marketplace-stats
    image: jansorg/jetbrains-marketplace-stats:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
        # -- Required ---: You have to add your own JetBrains Marketplace API key here
      - MARKETPLACE_API_KEY=your-api-key
        # Defines which currency is used to display monetary amounts
      - MARKETPLACE_DISPLAY_CURRENCY=USD
      - MARKETPLACE_SERVER_PORT=8080
        # none, normal or verbose
      - MARKETPLACE_LOG_LEVEL=none
        # language settings, change this to configure formatting of numbers and currency amounts
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
