services:
  jetbrains-marketplace-stats:
    container_name: jetbrains-marketplace-stats
    image: jansorg/jetbrains-marketplace-stats:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # You have to add your own JetBrains Marketplace API key here
      - MARKETPLACE_API_KEY=your-api-key

  frankfurter:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - frankfurter-cache:/var/lib/postgresql/data

volumes:
  frankfurter-cache: